version: '3'

services:
  jekyll:
    image: jekyll/jekyll:4.0
    ports:
        - "4000:4000"
    volumes:
        - .:/srv/jekyll
    environment:
       - JEKYLL_ENV=stage
    command: jekyll serve --force_polling --watch --drafts
